### ISSUE TITLE
Comments.php - end h2 when no beginning h2

### ISSUE THREAD

**Issue by gregoryhammond** [losol/positor#1]
Noticed on line 36 of comments.php that it is `</h2>,` when there is no h2 before it. I think it should be `</h4>`.

Thanks for the cool theme and for having it under an open-source license.

**Comment by losolio** [comment]
@gregoryhammond Thanks for your bug submission, it is appreciated. The error is now fixed. Please keep on submitting bugs and issues if you have. 

Feel free to make feature requests as well!
